import { useEffect } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, BookOpen, CalendarDays, GraduationCap, Handshake, Scale, Sparkles, Users } from "lucide-react";
import { EVENT_POSTS, getEventPostPath } from "../data/eventPosts.js";
import { getHomePageSeo, setPageSeo } from "../utils/seo.js";
import "./LandingPage.css";
import "./HomeV2.css";

const PROGRAMMES = [
  { icon: GraduationCap, title: "Professional development", text: "Peer learning, educator development and practice-led knowledge exchange.", to: "/programmes" },
  { icon: Users, title: "Mentorship & leadership", text: "Connecting experience with emerging educators, trainers and future leaders.", to: "/programmes" },
  { icon: BookOpen, title: "Education & outreach", text: "Taking fashion education, career awareness and learner support into institutions and communities.", to: "/programmes" },
  { icon: Handshake, title: "Industry collaboration", text: "Building practical bridges between educators, institutions and Ghana's fashion industry.", to: "/partners" },
  { icon: Scale, title: "Advocacy & representation", text: "Improving professional visibility and representation for women in fashion education and training.", to: "/programmes" },
  { icon: Sparkles, title: "Sustainability & innovation", text: "Sharing ideas around responsible practice, entrepreneurship, technology and future skills.", to: "/programmes" },
];
const LEADERS = [
  { image: "/card/v1.jpg", name: "Phyllis Mensah (PhD)", role: "Director" },
  { image: "/card/v11.jpg", name: "Abena Okyerewaa Siaw", role: "President" },
  { image: "/card/v2.jpg", name: "Joyceline Dzordzi Esi Lawoe", role: "Vice President" },
  { image: "/card/v3.jpg", name: "Matilda Ekua Tawiah (Ms. Tilly)", role: "Secretary" },
];
function LandingPage() {
  useEffect(() => { setPageSeo(getHomePageSeo()); }, []);
  const latestStories = EVENT_POSTS.slice(0, 3);
  return <main className="home-v2">
    <section className="home-v2__hero"><div className="home-v2__hero-bg" aria-hidden="true"/><div className="container home-v2__hero-grid"><div className="home-v2__hero-copy"><p className="home-v2__eyebrow">Professional Women in Fashion Education &amp; Training</p><h1>Connecting women. Strengthening fashion education. Shaping industry.</h1><p className="home-v2__lead">ProWIFETA is a professional association bringing together educators, trainers, researchers and mentors to strengthen learning, leadership, collaboration and opportunity across Ghana's fashion ecosystem.</p><div className="home-v2__actions"><Link className="home-v2__primary" to="/membership">Join ProWIFETA <ArrowRight size={18}/></Link><Link className="home-v2__secondary" to="/programmes">Explore our work</Link></div></div><aside className="home-v2__hero-panel"><p className="home-v2__panel-label">What you can discover here</p><div className="home-v2__snapshot"><strong>{EVENT_POSTS.length}</strong><span>documented stories &amp; activities</span></div><div className="home-v2__snapshot"><strong>{LEADERS.length}+</strong><span>executive leaders highlighted</span></div><div className="home-v2__snapshot"><strong>6</strong><span>programme areas</span></div><Link to="/impact">See documented impact <ArrowRight size={16}/></Link></aside></div></section>
    <section className="home-v2__intro"><div className="container home-v2__split"><div><p className="home-v2__kicker">Why ProWIFETA</p><h2>A professional platform for the women shaping fashion learning.</h2></div><div><p>ProWIFETA connects professional practice with education. The association creates space for mentorship, educator development, institutional collaboration, advocacy and stronger links between classrooms and industry.</p><Link className="home-v2__text-link" to="/about">Learn about the association <ArrowRight size={16}/></Link></div></div></section>
    <section className="home-v2__programmes"><div className="container"><div className="home-v2__heading"><div><p className="home-v2__kicker">Our work</p><h2>Six areas turning the mission into action.</h2></div><Link className="home-v2__text-link" to="/programmes">All programmes <ArrowRight size={16}/></Link></div><div className="home-v2__programme-grid">{PROGRAMMES.map(({icon:Icon,title,text,to})=><Link className="home-v2__programme" to={to} key={title}><Icon size={26}/><h3>{title}</h3><p>{text}</p><span>Explore <ArrowRight size={15}/></span></Link>)}</div></div></section>
    <section className="home-v2__evidence"><div className="container"><div className="home-v2__heading home-v2__heading--light"><div><p className="home-v2__kicker">Evidence, not claims</p><h2>See ProWIFETA's work through documented activities.</h2></div><Link className="home-v2__text-link home-v2__text-link--light" to="/impact">Explore impact <ArrowRight size={16}/></Link></div><div className="home-v2__story-grid">{latestStories.map(post=><article className="home-v2__story" key={post.id}><img src={post.coverImage} alt="" loading="lazy"/><div><p className="home-v2__story-meta">{post.category} · {post.displayDate}</p><h3>{post.title}</h3><p>{post.excerpt}</p><Link to={getEventPostPath(post)}>Read the story <ArrowRight size={15}/></Link></div></article>)}</div><div className="home-v2__evidence-actions"><Link className="home-v2__primary" to="/events"><CalendarDays size={18}/> Events &amp; activities</Link><Link className="home-v2__secondary" to="/blog">News &amp; Insights</Link></div></div></section>
    <section className="home-v2__leadership"><div className="container"><div className="home-v2__heading"><div><p className="home-v2__kicker">Leadership</p><h2>Professionals guiding the association.</h2></div><Link className="home-v2__text-link" to="/leadership">Meet the full community <ArrowRight size={16}/></Link></div><div className="home-v2__leader-grid">{LEADERS.map(person=><article className="home-v2__leader" key={person.name}><img src={person.image} alt={`Portrait of ${person.name}`} loading="lazy"/><div><p>{person.role}</p><h3>{person.name}</h3></div></article>)}</div></div></section>
    <section className="home-v2__partner"><div className="container home-v2__partner-grid"><div><p className="home-v2__kicker">Partnership in practice</p><h2>ProWIFETA × Ashanti Fashion Industry Network</h2><p>The association's MoU with AFIN provides concrete evidence of its commitment to mentorship, capacity building, entrepreneurship, innovation and stronger industry–education collaboration.</p></div><div className="home-v2__partner-actions"><Link className="home-v2__primary" to="/partners">Partner with ProWIFETA <ArrowRight size={18}/></Link><Link className="home-v2__secondary" to="/blog/prowifeta-afin-fashion-industry-partnership">Read the partnership story</Link></div></div></section>
    <section className="home-v2__opportunity"><div className="container home-v2__split"><div><p className="home-v2__kicker">Useful beyond the association</p><h2>Events, opportunities and knowledge in one place.</h2></div><div><p>Use ProWIFETA as a practical gateway to current association activities, verified opportunities and professional knowledge—not only as an archive of past events.</p><div className="home-v2__inline-links"><Link to="/events">Events</Link><Link to="/opportunities">Opportunities</Link><Link to="/blog">News &amp; Insights</Link></div></div></div></section>
    <section className="home-v2__join"><div className="container home-v2__join-inner"><div><p className="home-v2__kicker">Become part of ProWIFETA</p><h2>Build connections. Share expertise. Help shape the future of fashion education.</h2><p>Membership is designed for women contributing through teaching, research, mentorship, skills development, institutional leadership and related professional practice.</p></div><div className="home-v2__actions"><Link className="home-v2__primary" to="/membership">Membership &amp; application <ArrowRight size={18}/></Link><Link className="home-v2__secondary" to="/contact">Contact ProWIFETA</Link></div></div></section>
  </main>;
}
export default LandingPage;
